import json
import os
import re
from datetime import datetime

import anthropic
import yaml
from github import Github, GithubException

MODEL = "claude-haiku-4-5"
MAX_TOKENS = 4096


def _strip_ansi(text: str) -> str:
    return re.sub(r'\x1b\[[0-9;]*m', '', text)


def _read_model_files():
    files = {}
    for root, _, filenames in os.walk("dbt/models"):
        for filename in filenames:
            full_path = os.path.join(root, filename)
            try:
                with open(full_path) as f:
                    files[full_path] = f.read()
            except Exception:
                pass
    return files


def _determine_changed_files(fix_suggestion, model_files):
    files_text = "\n\n".join(
        f"### {path}\n{content}" for path, content in model_files.items()
    )
    prompt = (
        "Apply the following fix to the dbt model files listed below.\n"
        "Return ONLY a JSON object with this exact structure — no explanation, no markdown:\n"
        '{"changed_files": [{"path": "<relative path>", "content": "<full corrected file content>"}]}\n\n'
        f"Fix:\n{fix_suggestion}\n\n"
        f"Current files:\n{files_text}"
    )
    client = anthropic.Anthropic()
    response = client.messages.create(
        model=MODEL,
        max_tokens=MAX_TOKENS,
        messages=[{"role": "user", "content": prompt}],
    )
    text = next((b.text for b in response.content if hasattr(b, "text")), "")
    text = re.sub(r"^```[a-z]*\n?", "", text.strip())
    text = re.sub(r"\n?```$", "", text.strip())
    return json.loads(text)["changed_files"]


def open_pr(sandbox_result, error_entry, conversation_history):
    with open("config/github.yml") as f:
        gh_cfg = yaml.safe_load(f)
    owner = gh_cfg["owner"]
    repo_name = gh_cfg["repo"]
    token = os.environ["GITHUB_TOKEN"]

    timestamp = datetime.now().strftime("%Y%m%d-%H%M%S")
    branch_name = f"fix/dbt-error-{timestamp}"

    model_files = _read_model_files()
    changed_files = _determine_changed_files(sandbox_result["fix"], model_files)

    g = Github(token)
    gh_repo = g.get_repo(f"{owner}/{repo_name}")
    base_sha = gh_repo.get_branch(gh_repo.default_branch).commit.sha
    gh_repo.create_git_ref(f"refs/heads/{branch_name}", base_sha)

    commit_message = "fix: apply dbt fix from agent"
    for entry in changed_files:
        repo_path = f"pipeline/{entry['path']}"
        content = entry["content"]
        try:
            existing = gh_repo.get_contents(repo_path, ref=branch_name)
            gh_repo.update_file(repo_path, commit_message, content, existing.sha, branch=branch_name)
        except GithubException as e:
            if e.status == 404:
                gh_repo.create_file(repo_path, commit_message, content, branch=branch_name)
            else:
                raise

    pr_body = (
        f"## What failed\n"
        f"**Source:** {error_entry.get('source', 'unknown')}\n"
        f"**Message:** {error_entry.get('message', '')}\n"
        f"**Details:**\n```\n{_strip_ansi(error_entry.get('details', '') or '')}\n```\n\n"
        f"## Fix applied\n{sandbox_result.get('fix', '')}\n\n"
        f"## Sandbox attempts\n"
        f"Resolved in attempt {sandbox_result.get('attempt', '?')}/5\n\n"
        f"🤖 Generated by project-red agent"
    )

    pr = gh_repo.create_pull(
        title=f"fix: dbt error {timestamp}",
        body=pr_body,
        head=branch_name,
        base=gh_repo.default_branch,
    )
    return pr.html_url
